// Code generated by mockery v2.34.2. DO NOT EDIT.

package relationship

import (
	context "context"

	model "github.com/neygun/friend-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// CreateFriendConnection provides a mock function with given fields: ctx, friendConnReq
func (_m *MockService) CreateFriendConnection(ctx context.Context, friendConnReq FriendConnectionInput) (model.Relationship, error) {
	ret := _m.Called(ctx, friendConnReq)

	var r0 model.Relationship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, FriendConnectionInput) (model.Relationship, error)); ok {
		return rf(ctx, friendConnReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, FriendConnectionInput) model.Relationship); ok {
		r0 = rf(ctx, friendConnReq)
	} else {
		r0 = ret.Get(0).(model.Relationship)
	}

	if rf, ok := ret.Get(1).(func(context.Context, FriendConnectionInput) error); ok {
		r1 = rf(ctx, friendConnReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
