// Code generated by mockery v2.34.2. DO NOT EDIT.

package relationship

import (
	context "context"

	model "github.com/neygun/friend-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// CreateFriendConnection provides a mock function with given fields: ctx, friendConnReq
func (_m *MockService) CreateFriendConnection(ctx context.Context, friendConnReq FriendConnectionInput) (model.Relationship, error) {
	ret := _m.Called(ctx, friendConnReq)

	var r0 model.Relationship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, FriendConnectionInput) (model.Relationship, error)); ok {
		return rf(ctx, friendConnReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, FriendConnectionInput) model.Relationship); ok {
		r0 = rf(ctx, friendConnReq)
	} else {
		r0 = ret.Get(0).(model.Relationship)
	}

	if rf, ok := ret.Get(1).(func(context.Context, FriendConnectionInput) error); ok {
		r1 = rf(ctx, friendConnReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSubscription provides a mock function with given fields: ctx, createSubscriptionInput
func (_m *MockService) CreateSubscription(ctx context.Context, createSubscriptionInput CreateSubscriptionInput) (model.Relationship, error) {
	ret := _m.Called(ctx, createSubscriptionInput)

	var r0 model.Relationship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateSubscriptionInput) (model.Relationship, error)); ok {
		return rf(ctx, createSubscriptionInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateSubscriptionInput) model.Relationship); ok {
		r0 = rf(ctx, createSubscriptionInput)
	} else {
		r0 = ret.Get(0).(model.Relationship)
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateSubscriptionInput) error); ok {
		r1 = rf(ctx, createSubscriptionInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommonFriends provides a mock function with given fields: ctx, getCommonFriendsInput
func (_m *MockService) GetCommonFriends(ctx context.Context, getCommonFriendsInput GetCommonFriendsInput) ([]string, int, error) {
	ret := _m.Called(ctx, getCommonFriendsInput)

	var r0 []string
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, GetCommonFriendsInput) ([]string, int, error)); ok {
		return rf(ctx, getCommonFriendsInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, GetCommonFriendsInput) []string); ok {
		r0 = rf(ctx, getCommonFriendsInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, GetCommonFriendsInput) int); ok {
		r1 = rf(ctx, getCommonFriendsInput)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, GetCommonFriendsInput) error); ok {
		r2 = rf(ctx, getCommonFriendsInput)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetFriendsList provides a mock function with given fields: ctx, getFriendsInput
func (_m *MockService) GetFriendsList(ctx context.Context, getFriendsInput GetFriendsInput) ([]string, int, error) {
	ret := _m.Called(ctx, getFriendsInput)

	var r0 []string
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, GetFriendsInput) ([]string, int, error)); ok {
		return rf(ctx, getFriendsInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, GetFriendsInput) []string); ok {
		r0 = rf(ctx, getFriendsInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, GetFriendsInput) int); ok {
		r1 = rf(ctx, getFriendsInput)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, GetFriendsInput) error); ok {
		r2 = rf(ctx, getFriendsInput)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
