output   = "internal/repository/ormmodel"
wipe     = true
no-tests = true
add-enum-types = true
pkgname = "ormmodel"

[psql]
  dbname = "fm-pg"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  sslmode = "disable"
  blacklist = ["schema_migrations"]
